"use client";
import React, { useState, useMemo, useEffect } from 'react';

// Database bridge imported here!
import { supabase } from '@/lib/supabaseClient';

// --- TYPES (Supabase Ready) ---
interface ClientSnippet {
  id: number; // Matches the int8 in your database
  name: string;
}

interface BodyMetric {
  id?: string; // uuid generated by db
  client_id: number; // Foreign Key to Clients table
  date: string;
  body_weight: number;
  muscle_mass: number;
  fat_mass: number;
  notes: string;
}

export default function BodyMetrics() {
  // --- LIVE DATABASE STATE ---
  const [metrics, setMetrics] = useState<BodyMetric[]>([]);
  const [clientsList, setClientsList] = useState<ClientSnippet[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  
  // Form & Editing State
  const [formData, setFormData] = useState<Partial<BodyMetric>>({ date: new Date().toISOString().split('T')[0] });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // Two-Step Delete State
  const [isConfirmingDelete, setIsConfirmingDelete] = useState(false);

  // Searchable Dropdown State
  const [clientSearch, setClientSearch] = useState('');
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  // --- LIVE DATABASE FETCH ---
  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setIsLoading(true);
    try {
      // Fetch both tables at the same time for maximum speed
      const [clientsResponse, metricsResponse] = await Promise.all([
        supabase.from('clients').select('id, name').order('name'),
        supabase.from('body_metrics').select('*').order('date', { ascending: false })
      ]);

      if (clientsResponse.data) setClientsList(clientsResponse.data);
      if (metricsResponse.data) setMetrics(metricsResponse.data);
    } catch (error) {
      console.error("Error fetching data:", error);
    } finally {
      setIsLoading(false);
    }
  };

  // --- DERIVED DATA & CALCULATIONS ---
  const filteredClients = useMemo(() => {
    return clientsList.filter(c => c.name.toLowerCase().includes(clientSearch.toLowerCase()));
  }, [clientSearch, clientsList]);

  const totalLogs = metrics.length;
  
  // Safely calculate averages, defaulting to 0 if no logs exist
  const avgFatMass = totalLogs > 0 
    ? (metrics.reduce((acc, curr) => acc + (curr.fat_mass || 0), 0) / totalLogs).toFixed(1) 
    : "0.0";
    
  const avgMuscleMass = totalLogs > 0 
    ? (metrics.reduce((acc, curr) => acc + (curr.muscle_mass || 0), 0) / totalLogs).toFixed(1) 
    : "0.0";

  // --- HANDLERS ---
  const handleClientSelect = (clientId: number, clientName: string) => {
    setFormData({ ...formData, client_id: clientId });
    setClientSearch(clientName);
    setIsDropdownOpen(false);
  };

  const handleEdit = (metric: BodyMetric) => {
    setEditingId(metric.id!);
    setFormData(metric);
    const client = clientsList.find(c => c.id === metric.client_id);
    setClientSearch(client ? client.name : '');
    setIsConfirmingDelete(false); // Reset delete state
    // Scroll to top where form is
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleCancelEdit = () => {
    setEditingId(null);
    setFormData({ date: new Date().toISOString().split('T')[0] });
    setClientSearch('');
    setIsConfirmingDelete(false);
  };

  const handleDelete = async () => {
    if (!editingId) return;
    
    try {
      const { error } = await supabase.from('body_metrics').delete().eq('id', editingId);
      if (error) throw error;
      
      // Update UI instantly
      setMetrics(metrics.filter(m => m.id !== editingId));
      handleCancelEdit();
    } catch (error) {
      console.error("Error deleting metric:", error);
      alert("Failed to delete log.");
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.client_id) {
      alert("Please select a valid client from the dropdown.");
      return;
    }

    setIsSubmitting(true);
    try {
      // Clean up payload to match DB types perfectly
      const payload = {
        client_id: formData.client_id,
        date: formData.date,
        body_weight: parseFloat(formData.body_weight?.toString() || '0'),
        muscle_mass: parseFloat(formData.muscle_mass?.toString() || '0'),
        fat_mass: parseFloat(formData.fat_mass?.toString() || '0'),
        notes: formData.notes || ''
      };

      if (editingId) {
        // UPDATE Existing Log
        const { error } = await supabase
          .from('body_metrics')
          .update(payload)
          .eq('id', editingId);
          
        if (error) throw error;
      } else {
        // INSERT New Log
        const { error } = await supabase
          .from('body_metrics')
          .insert([payload]);
          
        if (error) throw error;
      }
      
      // Refresh real data from DB
      await fetchData();
      handleCancelEdit(); // Resets the form cleanly
    } catch (error) {
      console.error("Error saving metric:", error);
      alert("Failed to save metric to database.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      
      {/* --- HEADER --- */}
      <div>
        <h2 style={{ margin: 0, color: '#111827', fontSize: '1.8rem' }}>Body Metrics</h2>
        <p style={{ margin: '4px 0 0 0', color: '#6b7280' }}>Track composition changes over time.</p>
      </div>

      {/* --- 1. TOP VISUALIZATIONS --- */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px' }}>
        
        {/* KPI Summary */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div style={{ background: '#fff', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', borderLeft: '4px solid #2563eb' }}>
             <h4 style={{ margin: '0 0 4px 0', color: '#6b7280', fontSize: '0.85rem' }}>Total Logs Recorded</h4>
             <span style={{ fontSize: '2rem', fontWeight: 'bold', color: '#111827' }}>{totalLogs}</span>
          </div>
          <div style={{ background: '#fff', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', borderLeft: '4px solid #10b981' }}>
             <h4 style={{ margin: '0 0 4px 0', color: '#6b7280', fontSize: '0.85rem' }}>App-Wide Avg Fat %</h4>
             <span style={{ fontSize: '2rem', fontWeight: 'bold', color: '#111827' }}>{avgFatMass}%</span>
          </div>
          <div style={{ gridColumn: 'span 2', background: '#fff', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', borderLeft: '4px solid #8b5cf6' }}>
             <h4 style={{ margin: '0 0 4px 0', color: '#6b7280', fontSize: '0.85rem' }}>App-Wide Avg Muscle Mass</h4>
             <span style={{ fontSize: '2rem', fontWeight: 'bold', color: '#111827' }}>{avgMuscleMass} kg</span>
          </div>
        </div>

        {/* SVG Trend Chart Visualization (Static Sample) */}
        <div style={{ background: '#fff', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)' }}>
          <h4 style={{ margin: '0 0 16px 0', color: '#374151' }}>Overall Weight Trend (Sample)</h4>
          <div style={{ position: 'relative', height: '180px', width: '100%', marginTop: '10px' }}>
            <svg viewBox="0 0 400 180" preserveAspectRatio="none" style={{ width: '100%', height: '100%' }}>
              <path d="M0,45 L400,45 M0,90 L400,90 M0,135 L400,135" stroke="#e5e7eb" strokeWidth="1" strokeDasharray="4,4" />
              <path d="M0,150 L80,130 L160,140 L240,90 L320,60 L400,50" fill="none" stroke="#2563eb" strokeWidth="4" />
              <path d="M0,150 L80,130 L160,140 L240,90 L320,60 L400,50 L400,180 L0,180 Z" fill="rgba(37,99,235,0.1)" />
              <circle cx="80" cy="130" r="5" fill="#2563eb" />
              <circle cx="160" cy="140" r="5" fill="#2563eb" />
              <circle cx="240" cy="90" r="5" fill="#2563eb" />
              <circle cx="320" cy="60" r="5" fill="#2563eb" />
              <circle cx="400" cy="50" r="5" fill="#2563eb" />
            </svg>
          </div>
        </div>
      </div>

      {/* --- 2. LOG ENTRY FORM --- */}
      <div style={{ background: '#fff', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)', padding: '24px', borderTop: editingId ? '4px solid #f59e0b' : '4px solid #10b981' }}>
        <h3 style={{ margin: '0 0 20px 0', color: '#111827' }}>
          {editingId ? '✏️ Edit Metric Log' : '➕ Log New Metrics'}
        </h3>
        
        <form onSubmit={handleSave} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          
          {/* Custom Searchable Dropdown */}
          <div style={{ position: 'relative', gridColumn: 'span 1' }}>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 'bold', marginBottom: '6px', color: '#374151' }}>Client Name</label>
            <input 
              type="text" 
              placeholder="Search client..." 
              value={clientSearch}
              onChange={(e) => {
                setClientSearch(e.target.value);
                setFormData({ ...formData, client_id: undefined }); // Clear ID if typing
                setIsDropdownOpen(true);
              }}
              onFocus={() => setIsDropdownOpen(true)}
              onBlur={() => setTimeout(() => setIsDropdownOpen(false), 200)} // Delay to allow click
              style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '8px', boxSizing: 'border-box' }} 
              required 
            />
            {isDropdownOpen && (
              <div style={{ position: 'absolute', top: '100%', left: 0, right: 0, background: '#fff', border: '1px solid #d1d5db', borderRadius: '8px', marginTop: '4px', zIndex: 10, maxHeight: '150px', overflowY: 'auto', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' }}>
                {filteredClients.length > 0 ? (
                  filteredClients.map(client => (
                    <div 
                      key={client.id} 
                      onClick={() => handleClientSelect(client.id, client.name)}
                      style={{ padding: '10px', cursor: 'pointer', borderBottom: '1px solid #f3f4f6' }}
                    >
                      {client.name}
                    </div>
                  ))
                ) : (
                  <div style={{ padding: '10px', color: '#6b7280', fontSize: '0.85rem' }}>No clients found.</div>
                )}
              </div>
            )}
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 'bold', marginBottom: '6px', color: '#374151' }}>Date</label>
            <input required type="date" value={formData.date || ''} onChange={e => setFormData({...formData, date: e.target.value})} style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '8px', boxSizing: 'border-box' }} />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 'bold', marginBottom: '6px', color: '#374151' }}>Body Weight (kg)</label>
            <input required type="number" step="0.1" placeholder="0.0" value={formData.body_weight || ''} onChange={e => setFormData({...formData, body_weight: parseFloat(e.target.value)})} style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '8px', boxSizing: 'border-box' }} />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 'bold', marginBottom: '6px', color: '#374151' }}>Muscle Mass (kg)</label>
            <input required type="number" step="0.1" placeholder="0.0" value={formData.muscle_mass || ''} onChange={e => setFormData({...formData, muscle_mass: parseFloat(e.target.value)})} style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '8px', boxSizing: 'border-box' }} />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 'bold', marginBottom: '6px', color: '#374151' }}>Fat Mass (%)</label>
            <input required type="number" step="0.1" placeholder="0.0" value={formData.fat_mass || ''} onChange={e => setFormData({...formData, fat_mass: parseFloat(e.target.value)})} style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '8px', boxSizing: 'border-box' }} />
          </div>

          <div style={{ gridColumn: '1 / -1' }}>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 'bold', marginBottom: '6px', color: '#374151' }}>Notes (Optional)</label>
            <input type="text" placeholder='e.g., "Taken before breakfast", "Felt bloated"' value={formData.notes || ''} onChange={e => setFormData({...formData, notes: e.target.value})} style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '8px', boxSizing: 'border-box' }} />
          </div>

          {/* Form Footer with Safe Delete Integration */}
          <div style={{ gridColumn: '1 / -1', display: 'flex', gap: '12px', justifyContent: 'space-between', marginTop: '8px' }}>
            
            {/* Left Side: Delete Option (Only when editing) */}
            <div>
              {editingId && (
                isConfirmingDelete ? (
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ color: '#ef4444', fontSize: '0.85rem', fontWeight: 'bold' }}>Delete log?</span>
                    <button type="button" onClick={handleDelete} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}>Yes</button>
                    <button type="button" onClick={() => setIsConfirmingDelete(false)} style={{ padding: '8px 16px', background: '#f3f4f6', color: '#4b5563', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}>Cancel</button>
                  </div>
                ) : (
                  <button type="button" onClick={() => setIsConfirmingDelete(true)} style={{ padding: '10px 16px', background: '#fee2e2', color: '#991b1b', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}>
                    Delete Log
                  </button>
                )
              )}
            </div>

            {/* Right Side: Save & Cancel Edit */}
            <div style={{ display: 'flex', gap: '12px' }}>
              {editingId && (
                <button type="button" onClick={handleCancelEdit} style={{ padding: '10px 24px', background: '#f3f4f6', color: '#4b5563', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}>Cancel Edit</button>
              )}
              <button type="submit" disabled={isSubmitting} style={{ padding: '10px 24px', background: editingId ? '#f59e0b' : '#10b981', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', opacity: isSubmitting ? 0.7 : 1 }}>
                {isSubmitting ? 'Saving...' : (editingId ? 'Update Log' : 'Save Metric Log')}
              </button>
            </div>
          </div>

        </form>
      </div>

      {/* --- 3. RECENT LOGS TABLE --- */}
      <div style={{ background: '#fff', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
        <div style={{ padding: '20px', borderBottom: '1px solid #e5e7eb' }}>
          <h3 style={{ margin: 0, color: '#111827' }}>Recent Metric Logs</h3>
        </div>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', minWidth: '800px' }}>
            <thead style={{ background: '#f9fafb' }}>
              <tr style={{ color: '#6b7280', fontSize: '0.85rem', textTransform: 'uppercase' }}>
                <th style={{ padding: '16px 20px', fontWeight: 'bold' }}>Date</th>
                <th style={{ padding: '16px 20px', fontWeight: 'bold' }}>Client</th>
                <th style={{ padding: '16px 20px', fontWeight: 'bold' }}>Weight (kg)</th>
                <th style={{ padding: '16px 20px', fontWeight: 'bold' }}>Muscle (kg)</th>
                <th style={{ padding: '16px 20px', fontWeight: 'bold' }}>Fat (%)</th>
                <th style={{ padding: '16px 20px', fontWeight: 'bold' }}>Notes</th>
                <th style={{ padding: '16px 20px', fontWeight: 'bold', textAlign: 'right' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan={7} style={{ padding: '24px', textAlign: 'center', color: '#6b7280' }}>Loading metric logs from database...</td>
                </tr>
              ) : metrics.length === 0 ? (
                <tr>
                  <td colSpan={7} style={{ padding: '24px', textAlign: 'center', color: '#6b7280' }}>No body metrics logged yet.</td>
                </tr>
              ) : (
                metrics.map(metric => {
                  const clientName = clientsList.find(c => c.id === metric.client_id)?.name || 'Unknown Client';
                  return (
                    <tr key={metric.id} style={{ borderBottom: '1px solid #e5e7eb', backgroundColor: editingId === metric.id ? '#fef3c7' : 'transparent', transition: 'background 0.2s' }}>
                      <td style={{ padding: '16px 20px', fontWeight: 'bold', color: '#374151' }}>{metric.date}</td>
                      <td style={{ padding: '16px 20px', fontWeight: 'bold', color: '#2563eb' }}>{clientName}</td>
                      <td style={{ padding: '16px 20px', color: '#111827' }}>{metric.body_weight}</td>
                      <td style={{ padding: '16px 20px', color: '#111827' }}>{metric.muscle_mass}</td>
                      <td style={{ padding: '16px 20px', color: '#111827' }}>{metric.fat_mass}%</td>
                      <td style={{ padding: '16px 20px', color: '#6b7280', fontSize: '0.85rem', maxWidth: '200px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {metric.notes || '-'}
                      </td>
                      <td style={{ padding: '16px 20px', textAlign: 'right' }}>
                        <button onClick={() => handleEdit(metric)} style={{ padding: '6px 16px', background: 'transparent', color: '#f59e0b', border: '1px solid #fcd34d', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
                          Edit
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}